In [27]:
import pandas as pd
import numpy as np

In [204]:
codes = pd.read_csv('./code.csv',sep='\n',header=None)
keypad = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print keypad

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [205]:
diamond = np.matrix([[-1,-1,1,-1,-1],
                     [-1,2,3,4,-1],
                     [5,6,7,8,9],
                     [-1,'A','B','C',-1],
                     [-1,-1,'D',-1,-1]])
print diamond

[['-1' '-1' '1' '-1' '-1']
 ['-1' '2' '3' '4' '-1']
 ['5' '6' '7' '8' '9']
 ['-1' 'A' 'B' 'C' '-1']
 ['-1' '-1' 'D' '-1' '-1']]


In [206]:
def instruction2direction(instruction):
    if(instruction == 'L'):
        return (-1,0)
    elif(instruction == 'R'):
        return (1,0)
    elif(instruction == 'U'):
        return (0,-1)
    elif(instruction == 'D'):
        return (0,1)

In [207]:
def validate(keypad,pos,instruction):
    candidate = tuple(map(sum, zip(pos,instruction)))
    if candidate[0] < 0 or candidate[1] < 0:
        return False
    elif candidate[0] >= keypad.shape[0] or candidate[1] >= keypad.shape[1]:
        return False
    
    candidate_code = keypad.item(candidate[0],candidate[1])
    try:
        if int(candidate_code) == -1:
            return False
        else:
            return True
    except:
        return True

In [209]:
row = 0
col = 2

print 'starting position: ' + str(diamond.item((col,row)))

# iterate through the codes
for code in codes[0]:
    #iterate through the instructions
    for instruction in list(code):
        # get the instruction
        (drow,dcol) = instruction2direction(instruction)
        if validate(diamond,(col,row),(dcol,drow)):
            col += dcol
            row += drow
    print 'Key: ' + str(diamond.item(col,row))

starting position: 5
Key: D
Key: D
Key: 4
Key: 8
Key: 3
